service: e-and-b-solutions

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless
  stage: prod
  region: us-east-1
  environment:
    NODE_ENV: prod

functions:
  server:
    handler: index.server
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-apigw-binary
  - serverless-domain-manager

custom:
  secrets: ${file(secrets.json)}
  apigwBinary:
    types:
      - "*/*"
  customDomain:
    domainName: ${self:custom.secrets.prod.DOMAIN}
    basePath: ""
    stage: prod
    createRoute53Record: true
